# Generated by Django 3.1.4 on 2021-01-25 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20210125_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, default='post.png', upload_to='thumbnails'),
        ),
    ]
