# Generated by Django 3.1.4 on 2021-01-26 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20210125_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, default='thumbnails/post.png', upload_to='thumbnails'),
        ),
    ]
