# Generated by Django 3.1.4 on 2021-01-26 23:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20210126_1836'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('UUID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='post.post')),
                ('question1', models.CharField(max_length=400)),
                ('question2', models.CharField(blank=True, max_length=400)),
                ('question3', models.CharField(blank=True, max_length=400)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='value',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
