# Generated by Django 3.1.4 on 2021-01-27 00:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20210126_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='UUID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
