# Generated by Django 3.1.4 on 2021-01-27 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20210126_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.URLField(),
        ),
    ]
