# Generated by Django 3.1.4 on 2020-12-04 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='organization',
            table='Organization',
        ),
        migrations.AlterModelTable(
            name='student',
            table='Student',
        ),
    ]
